{
 "title": "Data Drift and Prediction Issues",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Predictions by Source",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "airflow_db",
     "rawSql": "SELECT\r\n  source as \"Source\",\r\n  COUNT(*) as \"Total Predictions\"\r\nFROM diabetes_data\r\nWHERE timestamp > NOW() - INTERVAL '30 minutes'\r\nGROUP BY source;"
    }
   ]
  },
  {
   "title": "Average Predictions - Last 30 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "airflow_db",
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  AVG(prediction) as \"Average Prediction\"\r\nFROM diabetes_data\r\nWHERE timestamp > NOW() - INTERVAL '30 minutes'\r\nGROUP BY timestamp\r\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Average Feature Values ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airflow_db",
     "rawSql": "SELECT\r\n  AVG(glucose) as \"Avg Glucose\",\r\n  AVG(bloodpressure) as \"Avg Blood Pressure\",\r\n  AVG(bmi) as \"Avg BMI\"\r\nFROM diabetes_data\r\nWHERE timestamp > NOW() - INTERVAL '30 minutes';"
    }
   ]
  },
  {
   "title": "Prediction Distribution - Last 30 Minutes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "airflow_db",
     "rawSql": "SELECT\r\n  prediction::text as \"Prediction\",\r\n  COUNT(*) as \"Count\"\r\nFROM diabetes_data\r\nWHERE timestamp > NOW() - INTERVAL '30 minutes'\r\nGROUP BY prediction;"
    }
   ]
  }
 ]
}