version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airflow_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    networks:
      - dsp_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - dsp_network

 # api:
   # build:
   #   context: ./api
   # container_name: fastapi-service
   # ports:
    #  - "8000:8000"
   # volumes:
   #   - ./api:/app
   # depends_on:
   #   - postgres
   # environment:
    #  - DATABASE_URL=postgresql://admin:admin@postgres:5432/airflow_db
   # networks:
     # - dsp_network

volumes:
  postgres-data:
  pgadmin_data:

networks:
  dsp_network:
    driver: bridge
